version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: lome
        restart: always
        environment:
           - MONGO_INITDB_ROOT_USERNAME: weykon
           - MONGO_INITDB_ROOT_PASSWORD: weykon
           - MONGO_INITDB_DATABASE: db
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro